# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Mashrabbek Akbarov
title: Fullstack Software Developer
email: akbarov.dev@gmail.com
website: mashrabbek.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: mashrabj0n
github_username: mashrabbek
stackoverflow_username: "10593484/mashrabjon"
linkedin_username: mashrabjon-akbarov-41a3a1146
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
  - title: itsgoingto.be
    icon: fas fa-code
    url: https://leetcode.com/mashrabjon/

# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Mashrabbek and I'm a software developer with over 3 years experience on creating web apps and services. I have worked at a number of companies gaining teamwork and leadership skills.

  I am most skilled in: <mark>Nodejs</mark> and <mark>Vuejs</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Personal Cabinet
        quote: >
          Personal Cabinet for bank workers.
        description: | # this will include new lines to allow paragraphs
          Created for NBU workers for optimizing work efficiency. Includes tasks module, accounting and monitoring IT devices, phone library, self assessment testing, finance and more.
          - Responsible for creating Rest Apis
          - Writing procedures on database
          - Auth System configurations
          - Code Review
          <mark> Tech Stack:  Exressjs(Nodejs), Vuejs (Quasar framework), Postgresql, Socket.io, Redis</mark>
      - layout: top-middle
        title: Docflow
        #link: github.com/sproogen
        # link_text: Project Website
        #additional_links:
        #  - title: sproogen/modern-resume-theme
        #    icon: fab fa-github
        #    url: github.com/sproogen/modern-resume-theme
        # - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #   icon: fab fa-github
        #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Document flow, task assignment system.
        description: | # this will include new lines to allow paragraphs
          - Created Rest Api Endpoints
          - Notification module using websockets
          - File UI module
          <mark> Tech Stack:  Spring Boot, Angular 6+, Oracle </mark>

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: National Bank of Uzbekistan
        link: nbu.uz
        # link_text: boringcompany.com
        sub_title: Software Developer
        caption: May 2019 - Present
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.
      - layout: left
        title: Fido Biznes
        link: http://www.fido-biznes.uz/
        # link_text: boringcompany.com
        sub_title: Senior Network System Administrator
        caption: November 2017 - Present
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Inha University in Tashkent
        caption: 2014 - 2018
        sub_title: BSc Computer Science & Engineering
        #quote: >
        #  Established in 2014,  United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          During my time at University I got courses from highly qualified prefessors. Finished course projects which helped me working in team and self studying. 
          - Founders' Grant Holder
          - Dean List Member in 2016
      - layout: left
        title: Academic lyceum
        caption: 2010 - 2013
        sub_title: Exact Sciences
        #quote: >
        #  Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          Learnt Math and Physics deeply which in turn helped to learn coding skills easy.
          - Local Physics olympiad participant
  - title: Awards & Certificates
    layout: text
    content: |
      - JS
  - title: Skills
    layout: text
    content: |
      - <mark>Nodejs</mark>
      - Expressjs
      - Vuejs
      - Postgresql
      - Redis
      - Docker
      - Socket.io
      - Typescript
      - Git
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      (/images/landscape-trees.jpg "Trees")
      ![Trees](/images/landscape-trees.jpg "Trees")  ![Trees](/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
