# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Mashrabbek Akbarov
title: Fullstack Software Developer
email: akbarov.dev@gmail.com
website: mashrabbek.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: mashrabj0n
github_username: mashrabbek
stackoverflow_username: "10593484/mashrabjon"
linkedin_username: mashrabjon-akbarov-41a3a1146
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
  - title: itsgoingto.be
    icon: fas fa-code
    url: https://leetcode.com/mashrabjon/

# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Mashrabbek and I'm a software developer with over 3 years experience on creating web apps and services. I have worked at a number of companies gaining teamwork and leadership skills.

  I am most skilled in: <mark>Nodejs</mark> and <mark>Vuejs</mark>

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: National Bank of Uzbekistan
        link: nbu.uz
        # link_text: boringcompany.com
        sub_title: Software Developer
        caption: May 2019 - Present
      - layout: left
        title: Fido Biznes
        link: http://www.fido-biznes.uz/
        # link_text: boringcompany.com
        sub_title: Junior Developer
        caption: December 2018 - May 2019
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Inha University in Tashkent
        caption: 2014 - 2018
        sub_title: BSc Computer Science & Engineering
        #quote: >
        #  Established in 2014,  United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          During my time at University I got courses from highly qualified prefessors. Finished course projects which later helped me on working in team and self studying. 
          - Founders' Grant Holder
          - Dean List Member in 2016
      - layout: left
        title: Academic lyceum
        caption: 2010 - 2013
        sub_title: Exact Sciences
        #quote: >
        #  Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          Learnt Math and Physics deeply which in turn helped to learn coding skills easy.
          - Local Physics olympiad participant
  - title: Awards & Certificates
    layout: text
    content: |
      <figure style="display: inline-block">
        <img src="/images/grant.jpg" alt="drawing" width="400" heigth="600"/>
        <figcaption>Founder's Grant Scholarship</figcaption>
      </figure>
      <figure style="display: inline-block">
        <img src="/images/dean.jpg" alt="drawing" width="400" heigth="600"/>
        <figcaption>Academic award</figcaption>
      </figure>
      <figure style="display: inline-block">
        <img src="/images/kafolat.jpg" alt="drawing" width="400" heigth="600"/>
        <figcaption>Mobile App in Insurance</figcaption>
      </figure>
      <figure style="display: inline-block">
        <img src="/images/java.jpg" alt="drawing" width="400" heigth="600"/>
        <figcaption>Java Certificate</figcaption>
      </figure>
      <figure style="display: inline-block">
        <img src="/images/oracle.jpg" alt="drawing" width="400" heigth="600"/>
        <figcaption>Oracle Database Certificate</figcaption>
      </figure>
      <figure style="display: inline-block">
        <img src="/images/opensource.jpg" alt="drawing" width="400" heigth="600"/>
        <figcaption>Open Source SW Seminar</figcaption>
      </figure>
      <figure style="display: inline-block">
        <img src="/images/windows.jpg" alt="drawing" width="400" heigth="600"/>
        <figcaption>Windows Server Certificate</figcaption>
      </figure>
      <figure style="display: inline-block">
        <img src="/images/itil.jpg" alt="drawing" width="400" heigth="600"/>
        <figcaption>ITIL fundamentals Certificate</figcaption>
      </figure>
      
  - title: Skills
    layout: text
    content: |
      - Nodejs (Express.js, Nest.js)
      - Vuejs (Quasar, Vuetify)
      - Postgresql, Oracle, Mongodb
      - Redis
      - Docker
      - Socket.io
      - Typescript
      - Git
      - Java (Spring Boot)
      - ORM (Sequelize, TypeORM, Hibernate)
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in software engineering some of my other interests and hobbies are:
      - Competetive programmming
      - Gaming

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
